export const LABELS = {
  ACCOUNT_FUNDED: "Account funded.",
  APP_TITLE: "Sosol",
  AUDIT_WARNING:
    "Oyster is an unaudited software project used for internal purposes at the Solana Foundation. This app is not for public use.",
  BORROWED_VALUE: "You borrowed",
  BORROWING_POWER_USED: "Borrowing Power Used",
  BORROWING_POWER_VALUE: "Borrowing Power",
  BORROWS: "Borrows",
  BORROW_ACTION: "Borrow",
  BORROW_NOW: "Borrow now",
  BORROW_QUESTION: "How much would you like to borrow?",
  COLLATERAL: "Collateral",
  CONNECT_BUTTON: "Connect",
  CONNECT_LABEL: "Connect",
  DASHBOARD_ACTION: "Go to dashboard",
  DASHBOARD_INFO: "Connect to a wallet to view your deposits/loans.",
  DASHBOARD_TITLE_DEPOSITS: "Deposits",
  DASHBOARD_TITLE_LOANS: "Loans",
  DEPOSITS: "Deposits",
  DEPOSIT_ACTION: "Deposit",
  DEPOSIT_QUESTION: "How much would you like to deposit?",
  FAUCET_INFO:
    "This faucet will help you fund your accounts outside of Solana main network.",
  FOOTER:
    'This page was produced by the Solana Foundation ("SF") for internal educational and inspiration purposes only. SF does not encourage, induce or sanction the deployment, integration or use of Oyster or any similar application (including its code) in violation of applicable laws or regulations and hereby prohibits any such deployment, integration or use. Anyone using this code or a derivation thereof must comply with applicable laws and regulations when releasing related software.',
  GIVE_SOL: "Give me SOL",
  GO_BACK_ACTION: "Go back",
  LEVERAGE_LIMIT_MESSAGE: "You will need more margin to make this trade.",
  LIQUIDATE_ACTION: "Liquidate",
  LIQUIDATE_NO_LOANS: "There are no loans to liquidate.",
  LIQUIDATE_QUESTION: "How much would you like to liquidate?",
  LIQUIDATION_INFO:
    "This view displays all loans that can be liquidated. A liquidation is a process where borrower collateral does not cover value of the loan. It is represented by health factor falling below 1.0. When a loan is liquidated, an liquidator can purchase collateral at a discount by repaing the portio of the loan. ",
  LIQUIDATION_PENALTY: "Liquidation penalty",
  LIQUIDATION_THRESHOLD: "Liquidation threshold",
  LOAN_TO_VALUE: "Loan to value",
  MARGIN_TRADE_ACTION: "Margin Trade",
  MARGIN_TRADE_CHOOSE_COLLATERAL_AND_LEVERAGE:
    "Please choose your collateral and leverage.",
  MARGIN_TRADE_QUESTION:
    "Please choose how much of this asset you wish to purchase.",
  MARGIN_TRADING: "Margin Trading",
  MAX_LTV: "Maximum LTV",
  MENU_BORROW: "Borrow",
  MENU_DASHBOARD: "Dashboard",
  MENU_DEPOSIT: "Deposit",
  MENU_FAUCET: "Faucet",
  MENU_HOME: "Home",
  MENU_LIQUIDATE: "Liquidate",
  MENU_TRANSACTION: "Transactions",
  NOTHING_BORROWED: "Nothing borrowed yet",
  NOTHING_BORROWED_MESSAGE:
    "There will be a list of all the assets you have borrowed. For now, it's empty since you have not borrowed.",
  NOT_ENOUGH_MARGIN_MESSAGE:
    "Not enough buying power in oyster to make this trade at this leverage.",
  NO_COLLATERAL: "No collateral",
  NO_COLL_TYPE_MESSAGE: "Choose Collateral CCY",
  NO_DEPOSITS: "No deposits",
  NO_DEPOSIT_MESSAGE:
    "You need to deposit coin of this type into oyster before trading with it on margin.",
  NO_LOANS: "No loans",
  NO_LOANS_NO_DEPOSITS: "No loans or deposits.",
  REPAY_ACTION: "Repay",
  REPAY_QUESTION: "How much would you like to repay?",
  RESERVE_STATUS_TITLE: "Reserve Status & Configuration",
  RISKIER: "Riskier",
  SAFER: "Safer",
  SELECT_COLLATERAL: "Select collateral",
  SETTINGS_TOOLTIP: "Settings",
  SET_MORE_MARGIN_MESSAGE:
    "You need more margin to match this leverage amount to make this trade.",
  TABLE_TITLE_ACTION: "Action",
  TABLE_TITLE_APY: "APY",
  TABLE_TITLE_ASSET: "Asset",
  TABLE_TITLE_BORROWS: "Borrows",
  TABLE_TITLE_BORROW_APY: "Borrow APY",
  TABLE_TITLE_BUYING_POWER: "Total Buying Power",
  TABLE_TITLE_COLLATERAL_BALANCE: "Collateral",
  TABLE_TITLE_DEPOSITS: "Deposits",
  TABLE_TITLE_DEPOSIT_APY: "Deposit APY",
  TABLE_TITLE_DEPOSIT_BALANCE: "Your deposits",
  TABLE_TITLE_HEALTH: "Health Factor",
  TABLE_TITLE_LIQUIDATE_OBLIGATIONS: "Liquidate Obligations",
  TABLE_TITLE_LOAN_BALANCE: "Loan balance",
  TABLE_TITLE_LTV: "LTV",
  TABLE_TITLE_MARKET_SIZE: "Market Size",
  TABLE_TITLE_MAX_BORROW: "Available for you",
  TABLE_TITLE_REPAY_OBLIGATIONS: "Repay Obligations",
  TABLE_TITLE_TOTAL_BORROWED: "Total Borrowed",
  TABLE_TITLE_WITHDRAWS: "Withdraws",
  TABLE_TITLE_YOUR_LOAN_BALANCE: "Loan balance",
  TOTAL_TITLE: "Total",
  TRADING_ADD_POSITION: "Add Position",
  TRADING_TABLE_TITLE_ACTIONS: "Action",
  TRADING_TABLE_TITLE_APY: "APY",
  TRADING_TABLE_TITLE_ASSET_PRICE: "Asset Price",
  TRADING_TABLE_TITLE_DESIRED_ASSET: "Desired Asset",
  TRADING_TABLE_TITLE_LIQUIDATION_PRICE: "Liquidation Price",
  TRADING_TABLE_TITLE_MULTIPLIER: "Leverage",
  TRADING_TABLE_TITLE_MY_COLLATERAL: "Chosen Collateral",
  TRANSACTIONS_INFO: "Connect to a wallet to view your transactions.",
  WALLET_BALANCE: "Wallet balance",
  WALLET_TOOLTIP: "Wallet public key",
  WITHDRAW_ACTION: "Withdraw",
  WITHDRAW_QUESTION: "How much would you like to withdraw?",
};
