export enum RoutePath {
  DAO = "b",
  DAO_CHANNEL = "b/:channelId",
  DASHBOARD = "dash",
  EXPLORE = "explore",
  FEED = "feed",
  FOLLOWING = "following",
  HANDLE = "@/:handle",
  HANDLE_HASH = "@",
  HOME = "/",
  LAB = "lab",
  LEADERBOARD = "leaderboard",
  MEEP = "m/:tweetId",
  MEEP_HASH = "m",
  MINT_NFT = "mint-nft",
  NEWS = "news",
  NOTIFICATIONS = "notifications",
  PEOPLE = "people",
  PROFILE_SETTINGS = "settings/profile",
  WILDCARD = "*",
}
